
use caja_ahorro_bd;
-- Inserting data into ESTATUS_CUENTA table
-- Inserting data into ESTATUS_CUENTA table
INSERT INTO ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Activo', 'La cuenta está activa y en buen estado.');
INSERT INTO ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Inactivo', 'La cuenta está inactiva por algún motivo.');
INSERT INTO ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Bloqueado', 'La cuenta está bloqueada temporalmente.');
INSERT INTO ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Cerrado', 'La cuenta ha sido cerrada permanentemente.');
INSERT INTO ESTATUS_CUENTA (NOMBRE, DESCRIPCION) VALUES ('Pendiente', 'La cuenta está en espera de aprobación.');

SELECT * from estatus_cuenta;

-- Inserting data into ROL table
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('Admin', 'Administrator role with full access.');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('User', 'Standard user role with limited access.');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('Manager', 'Manager role with elevated privileges.');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('Guest', 'Guest role with minimal access.');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('Support', 'Support role for providing assistance.');

SELECT * from ROL;

-- Inserting data into USUARIO table
INSERT INTO USUARIO (EMAIL, CONTRASENA, APELLIDO_MATERNO, NUMERO_TELEFONICO, CALLE, ESTADO, ZIP, NOMBRE, APELLIDO_PATERNO, ROL_ID) 
VALUES ('user1@example.com', 'password1', 'Gonzalez', '1234567890', 'Calle 1', 'Ciudad', 12345, 'Juan', 'Perez', 1);

INSERT INTO USUARIO (EMAIL, CONTRASENA, APELLIDO_MATERNO, NUMERO_TELEFONICO, CALLE, ESTADO, ZIP, NOMBRE, APELLIDO_PATERNO, ROL_ID) 
VALUES ('user2@example.com', 'password2', 'Lopez', '9876543210', 'Calle 2', 'Ciudad', 54321, 'Maria', 'Rodriguez', 2);

INSERT INTO USUARIO (EMAIL, CONTRASENA, APELLIDO_MATERNO, NUMERO_TELEFONICO, CALLE, ESTADO, ZIP, NOMBRE, APELLIDO_PATERNO, ROL_ID) 
VALUES ('admin@example.com', 'adminpass', 'Admin', '5556667777', 'Admin Street', 'Admin City', 99999, 'Admin', 'Admin', 1);

INSERT INTO USUARIO (EMAIL, CONTRASENA, APELLIDO_MATERNO, NUMERO_TELEFONICO, CALLE, ESTADO, ZIP, NOMBRE, APELLIDO_PATERNO, ROL_ID) 
VALUES ('guest@example.com', 'guestpass', 'Guest', '1112223333', 'Guest Street', 'Guest City', 11111, 'Guest', 'Guest', 4);

INSERT INTO USUARIO (EMAIL, CONTRASENA, APELLIDO_MATERNO, NUMERO_TELEFONICO, CALLE, ESTADO, ZIP, NOMBRE, APELLIDO_PATERNO, ROL_ID) 
VALUES ('support@example.com', 'supportpass', 'Support', '9998887777', 'Support Street', 'Support City', 88888, 'Support', 'Support', 5);

SELECT * from USUARIO;

-- Inserting data into CUENTA table
INSERT INTO CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (1000, '2023-11-13 10:30:00', 1, 1);
INSERT INTO CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (500, '2023-11-14 12:45:00', 2, 2);
INSERT INTO CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (2000, '2023-11-15 08:15:00', 3, 1);
INSERT INTO CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (150, '2023-11-16 14:20:00', 4, 3);
INSERT INTO CUENTA (SALDO, FECHA_APERTURA, USUARIO_ID, ESTATUS_CUENTA_ID) VALUES (800, '2023-11-17 09:00:00', 5, 1);

SELECT * from CUENTA;

-- Inserting data into TRANSACCION table
INSERT INTO TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID) VALUES (50, '2023-11-13 11:00:00', 1, NULL, NULL);
INSERT INTO TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID) VALUES (200, '2023-11-14 13:30:00', 2, NULL, NULL);
INSERT INTO TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID) VALUES (1000, '2023-11-15 09:45:00', 3, NULL, NULL);
INSERT INTO TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID) VALUES (20, '2023-11-16 15:00:00', 4, NULL, NULL);
INSERT INTO TRANSACCION (MONTO, FECHA, CUENTA_ID, TIPO_TRANSACCION_ID, ESTATUS_TRANSACCION_ID) VALUES (300, '2023-11-17 10:20:00', 5, NULL, NULL);

SELECT * FROM TRANSACCION;