spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pixupdb
    username: pixup_owner
    password: pixup_password

jpa:
  show-sql: true
  open-in-view: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      format_sql: true


server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
